{% set version = '0.2.1' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-distributions3
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/distributions3_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/distributions3/distributions3_{{ version }}.tar.gz
  sha256: 0651dc32be8c4a016344cfe5c3aab5c0fb2d424acd1e1600ddf063a871d188a5

build:
  merge_build_host: True  # [win]
  number: 2
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-ellipsis
    - r-ggplot2
    - r-glue
  run:
    - r-base
    - r-ellipsis
    - r-ggplot2
    - r-glue

test:
  commands:
    - $R -e "library('distributions3')"           # [not win]
    - "\"%R%\" -e \"library('distributions3')\""  # [win]

about:
  home: https://alexpghayes.github.io/distributions3/
  dev_url: https://github.com/alexpghayes/distributions3
  license: MIT
  summary: Tools to create and manipulate probability distributions using S3.  Generics pdf(),
    cdf(), quantile(), and random() provide replacements for base R's d/p/q/r style
    functions.  Functions and arguments have been named carefully to minimize confusion
    for students in intro stats courses. The documentation for each distribution contains
    detailed mathematical notes.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
